Home And Welcome ViewModelTests
alkemyTech/OT219-Swift pull request #35
Opened 2022-06-17 19:52 UTC by adriancysvillegast

aqui adjunte algunos test para validar la data usada en homeViewModel, realice algunos cambios en el viewModel de testimonios para para poder realizar el test cabe destacar que mis conocimientos aqui son basicos pero todo anda bien. estare atento a los comentarios que puedan generar este pull request

2022-06-20 12:22 UTC, DavidDuarte22 commented
@adriancysvillegast te habrás olvidado de pusiera el .pbjproj porque no veo los archivos linkeados :)

2022-06-20 14:25 UTC, adriancysvillegast commented
> @adriancysvillegast te habrás olvidado de pusiera el .pbjproj porque no veo los archivos linkeados :)

disculpa, ya lo volvi a subir.

2022-06-21 13:55 UTC, DavidDuarte22 requested changes

2022-06-21 13:55 UTC, DavidDuarte22 commented on Test/Test_All_HomeViewModel.swift
> +    var homeViewModel : HomeViewModel!
en los unit tests se suele llamar sut (System Under Test) al objeto que estamos testeando, es por convencion. Pegale una mirada a Cris que ya se lo corregi a ese error. Por ese lado, veo que esta duplicado lo que el hizo (Test_Home_ViewModel), unificalo porfa :)

2022-06-22 18:20 UTC, adriancysvillegast commented
![Screen Shot 2022-06-22 at 2 17 23 PM](https://user-images.githubusercontent.com/81894293/175108753-694d904d-bcc7-453a-a959-3bbd8306400b.png)


listo ya realice los cambios e integración

2022-06-24 15:59 UTC, closed without merging