Feat/CristianCosta - Service Post in Contact
alkemyTech/OT219-Swift pull request #43
Opened 2022-06-23 20:52 UTC by cristian-costa

- Add func post request when user taps the button
- Add spinner when start post request and remove it when finish
- Change validation in message: automatically change state of button when user is writing the message. 

https://user-images.githubusercontent.com/80304059/175397379-d8f111db-11bc-4527-95b3-a69af6d2e9ef.mp4

2022-06-24 16:05 UTC, DavidDuarte22 requested changes

2022-06-24 16:05 UTC, DavidDuarte22 commented on SwiftTemplate/Modules/Contact/View/ContactViewController.swift
> +    private let loadingView: UIView = {
Cris no hace falta una vista para poner el spinner. Lo podes poner directamente sobre la self.view del vc. De hecho te va a quedar mas prolijo porque va a estar centrado, se ve en la grabacion que hiciste que no esta centrado en la vista

2022-06-24 16:05 UTC, DavidDuarte22 commented on SwiftTemplate/Modules/Contact/View/ContactViewController.swift
> +        showSpinner()
tambien podrias deshabilitar el boton hasta que no tengas una respuesta. Y en el delegate volver a habilitarlo

2022-06-24 18:26 UTC, cristian-costa commented on SwiftTemplate/Modules/Contact/View/ContactViewController.swift
> +        showSpinner()
Lo que me di cuenta es que el botón quedaba habilitado una vez hecha la petición, ahí una vez enviada puse en false las variables que se tenian en cuenta para habilitarlo y lo deshabilite.
https://user-images.githubusercontent.com/80304059/175640426-6ca3b7ee-5ac5-4695-a0c4-f20a40fa930e.mp4

2022-06-24 18:26 UTC, cristian-costa commented on SwiftTemplate/Modules/Contact/View/ContactViewController.swift
> +    private let loadingView: UIView = {
Hecho

2022-06-27 11:11 UTC, DavidDuarte22 approved these changes

2022-06-27 11:11 UTC, merged